db:
  host: '192.168.1.229'
  port: 3306
  user: 'dev'
  password: 'Awesome85**'
  name: 'municipality'

consumer:
  brokers: ['192.168.1.229:9092']
  topic: 'update.firebase.token'
  group_id: 'consumer.firebase.group'

cache:
  address: '192.168.1.229'
  port: ':6379'
  password: 'Awesome85**'
  db: 0
  pool_size: 25
  minimum_idle_connections: 10
  maximum_retries: 1
  token_key_format: 'token.%s'

health:
  port: ':8020'
  shutdown_endpoint: '/api/v1/consumer_firebase_token_health/shutdown'
  content_type: 'application/json'